### ISSUE TITLE
gatecli con-account create error

### ISSUE THREAD

**Issue by yan253319066** [gatechain/node-binary#5]
![image](https://user-images.githubusercontent.com/37472467/118913260-af59ea00-b95b-11eb-9085-338cfab48765.png)

[a ~]# gatecli con-account create gt11xvaxxx --chain-id mainnet
panic: open /root/.gatecli/api.token: no such file or directory

goroutine 1 [running]:
github.com/gatechain/gatechain/framework/client/context.NewCLIContextWithFrom(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/mnt/go/src/github.com/gatechain/gatechain/framework/client/context/context.go:85 +0x796
github.com/gatechain/gatechain/framework/client/context.NewCLIContext(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/mnt/go/src/github.com/gatechain/gatechain/framework/client/context/context.go:119 +0x9a
github.com/gatechain/gatechain/framework/x/staking/client/cli.GetCmdCreateValidator.func1(0xc000469180, 0xc00045d560, 0x1, 0x3, 0x0, 0x0)
	/mnt/go/src/github.com/gatechain/gatechain/framework/x/staking/client/cli/tx.go:165 +0x43
github.com/spf13/cobra.(*Command).execute(0xc000469180, 0xc00045d4a0, 0x3, 0x3, 0xc000469180, 0xc00045d4a0)
	/mnt/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000253680, 0x8909c0, 0xc000253680, 0x18b6b24)
	/mnt/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/mnt/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc000253680, 0x1af6f90, 0x2, 0xc000405510)
	/mnt/go/pkg/mod/github.com/tendermint/tendermint@v0.32.8/libs/cli/setup.go:89 +0x3c
main.main()
	/mnt/go/src/github.com/gatechain/gatechain/cmd/gatecli/main.go:109 +0xa2a
[a ~]# gatecli token list --chain-id mainnet
panic: open /root/.gatecli/api.token: no such file or directory

goroutine 1 [running]:
github.com/gatechain/gatechain/framework/client/context.NewCLIContextWithFrom(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/mnt/go/src/github.com/gatechain/gatechain/framework/client/context/context.go:85 +0x796
github.com/gatechain/gatechain/framework/client/context.NewCLIContext(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/mnt/go/src/github.com/gatechain/gatechain/framework/client/context/context.go:119 +0x9a
github.com/gatechain/gatechain/framework/x/token/client/cli.ListTokenCmd.func1(0xc001004c80, 0xc000fdd480, 0x0, 0x2, 0x0, 0x0)
	/mnt/go/src/github.com/gatechain/gatechain/framework/x/token/client/cli/query.go:75 +0x43
github.com/spf13/cobra.(*Command).execute(0xc001004c80, 0xc000fdd440, 0x2, 0x2, 0xc001004c80, 0xc000fdd440)
	/mnt/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000dcef00, 0x8909c0, 0xc000dcef00, 0x18b6b24)
	/mnt/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/mnt/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc000dcef00, 0x1af6f90, 0x2, 0xc000dbce80)
	/mnt/go/pkg/mod/github.com/tendermint/tendermint@v0.32.8/libs/cli/setup.go:89 +0x3c
main.main()
	/mnt/go/src/github.com/gatechain/gatechain/cmd/gatecli/main.go:109 +0xa2a

**Comment by mofeixiaobao** [comment]
启动gated，追上mainnet的高度，然后把/root/.gated/api.token 复制到/root/.gatecli/api.token

**Comment by yan253319066** [comment]
已解决
